version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-creator-ai
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # API Keys - set these in .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
      - GIPHY_API_KEY=${GIPHY_API_KEY}
      - UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}
    volumes:
      - ./logs:/app/logs
      - ./generated-videos:/app/generated-videos
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for rate limiting persistence
  redis:
    image: redis:7-alpine
    container_name: video-creator-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: